---
version: '3'
volumes:
  db-data:
    external: false
services:
  dev:

    build:
      context: '.'
      dockerfile: 'Dockerfile'

    command: 'tail -f /dev/null'
    ports:
      - 5000:5000
    volumes:
      - '.:/var/service:cached'
