---
version: '3'
services:
  dev:

    build:
      context: '.'
      dockerfile: 'Dockerfile'

    command: 'tail -f /dev/null'
    ports:
      - 5000:5000
    volumes:
      - '.:/var/service:cached'
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: project_stats
      POSTGRES_PASSWORD: project_stats
    volumes:
      - ./docker/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql


    ports:
      - 127.0.0.1:5432:5432
